version: '3.0'
services:
  chickadee-dev:
    image: pcic/chickadee:latest
    container_name: chickadee-dev
    environment:
      - PYWPS_CFG=/wps.cfg
    ports:
      - "30102:5000"
    volumes:
      - ./dev-component/wps.cfg:/wps.cfg
    restart: always

networks:
  default:
    external:
      name: pcicbr0


# docker-compose build
# docker-compose up
# docker-compose down
# docker-compose rm
