name: Python CI

on: push

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        PIP_INDEX_URL: https://pypi.pacificclimate.org/simple
      run: |
        sudo apt-get install libudunits2-dev
        sudo apt-get install libnetcdf-dev
        pip install -r requirements.txt
        pip install -e .[dev]
        ./r_install.sh
    - name: Test with pytest (full)
      if: github.ref == 'refs/heads/master'
      run: |
        py.test -m "not online" -v
    - name: Test with pytest (fast)
      if: github.ref != 'refs/heads/master'
      run: |
        py.test -m "not online and not slow" -v
    - name: Code Quality
      run: black . --check
